select review_uuid,
--       coming_from,
--       company_region,
       company_id,
       review_type,
--       review_id,
--       user_id,
--       employmenttype,
       review_creation_date,
--       review_update_time,
       active,
       active_part,
--       cached,
--       source_type,
--       confirmed,
--       title,
--       recommend,
       total_score,
       s_1,
       s_2,
       s_3,
       s_4,
       s_5,
       s_6,
       s_7,
       s_8,
       s_9,
       s_10,
       s_11,
       s_12,
       s_13,
       s_14,
       s_15,
       s_16,
       s_17,
       s_18,
--       review_benefits,
       job_status,
--       job_position,
--       job_department,
--       job_location,
--       ex_job,
--       prak_job,
--       ausbildung_als,
       comment,
       comment_1,
       comment_2,
       text_s1,
       text_s2,
       text_s3,
       text_s4,
       text_s5,
       text_s6,
       text_s7,
       text_s8,
       text_s9,
       text_s10,
       text_s11,
       text_s12,
       text_s13,
       text_s14,
       text_s15,
       text_s16,
       text_s17,
       text_s18,
       texts_count,
--       improvement_count,
       improvement_text,
--       has_review_text,
--       has_improvement_text,
--       text_criteria_count,
--       statement_creation_date,
--       statement_id,
--       statement_user_id,
--       statement_text,
--       statement_status,
--       statement_update_date,
       profile_uuid,
--       company_duns_id,
       company_name,
--       company_staedte_abgleich2_id,
--       company_land_permalink,
--       company_bundesland,
       company_stadt,
--       company_branche,
--       profile_vanityurl,
--       profile_name,
--       profile_gruppen_id,
--       profile_hash,
--       profile_kunden_id,
       profile_ebp_status,
--       profile_crm_kunden_id,
--       profile_land_permalink,
--       profile_bundesland,
--       profile_stadt,
--       profile_staedte_abgleich2_id,
--       profile_plz,
--       profile_external_url,
       profile_industry_id,
       profile_weighted_total,
--       profile_recommendation_rate,
--       profile_online_review_count,
--       profile_last_review_date,
--       profile_stellungnahmen_cnt,
--       profile_zugriffe,
--       profile_benefits,
       profile_url_short
--       profile_size,
--       profile_ebp_feature_is_deactivated,
--       coming_from_reportingCategory,
--       ga_channelGrouping,
--       ga_vwo_campaign,
--       ga_campaign,
--       ga_deviceCategory,
--       ga_source,
--       ga_medium,
--       ga_timeOnSite,
--       ga_duration_review_creation,
--       ga_session_pageviews,
--       ga_visitNumber,
--       ga_entrance_page_type,
--       review_uuid_hashed,
--       review_iso_creation_year,
--       review_iso_creation_week,
--       review_iso_update_year,
--       review_iso_update_week,
--       xplenty_load_timestamp,
--       xplenty_data_type

from pond.reviews as r
--    inner join lake.rds_mysql__profiles__profiles as p on r.company_id where p.industry_id not in (10)

where 1=1
--    and profile_uuid = '27df0abe-7d33-44cc-8e87-77341d31edfd'
--    and review_uuid = 'a581c3dc-d7cf-4ff4-bf76-5e948c6587b3'
  and active_part = 'alles'
  and active = '1'
  and company_land_permalink <> 'us'
  and has_review_text = 1
-- limit 100
